sudo: required
services:
  - docker
env:
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_681ac5accbf9_key -iv $encrypted_681ac5accbf9_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project mybarber-1534076248757
  - gcloud config set compute/zone europe-west3-a	
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t filip505/multi-client ./client
  - docker build -t filip505/multi-nginx ./nginx
  - docker build -t filip505/multi-server ./server
  - docker build -t filip505/multi-worker ./worker
  # Log in to the docke CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Take those images and push them to docker hub

  - docker push filip505/multi-client
  - docker push filip505/multi-nginx
  - docker push filip505/multi-server
  - docker push filip505/multi-worker

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
